// src/screens/LicensesScreen.js
// Credits and licences: symbol and data attributions, icon fonts, and the
// open-source notices for every package shipped in the app bundle
// (generated by scripts/generate-third-party-notices.js).

import React, { useState, useMemo } from 'react';
import { View, Text, FlatList, TouchableOpacity, StyleSheet, Linking } from 'react-native';
import { useSettings } from '../contexts/SettingsContext';
import { getPalette, spacing, radii } from '../theme';
import notices from '../data/thirdPartyNotices.json';

const CREDITS = [
  {
    id: 'arasaac',
    title: 'ARASAAC pictograms',
    body: "Pictograms' author: Sergio Palao. Origin: ARASAAC (https://arasaac.org). License: CC (BY-NC-SA). Owner: Government of Aragón (Spain). Pictograms are loaded from ARASAAC when online and shown unmodified.",
    link: { label: 'ARASAAC terms of use', url: 'https://arasaac.org/terms-of-use' },
  },
  {
    id: 'childes',
    title: 'Word prediction vocabulary',
    body: 'The on-device word prediction vocabulary is derived from child-language transcripts in the CHILDES database (TalkBank), used under the Creative Commons BY-NC-SA 3.0 licence. MacWhinney, B. (2000). The CHILDES Project: Tools for analyzing talk. 3rd Edition. Mahwah, NJ: Lawrence Erlbaum Associates.',
    link: { label: 'TalkBank data rules', url: 'https://talkbank.org/0share/rules.html' },
  },
  {
    id: 'icons',
    title: 'Icons',
    body: 'Ionicons (MIT License, © Ionic) and Material Icons (Apache License 2.0, © Google), via @expo/vector-icons. Licence texts are listed below.',
  },
];

function licenceTextsFor(pkg) {
  if (pkg.textId && notices.texts[pkg.textId]) return [notices.texts[pkg.textId]];
  // Packages published without a LICENSE file: show the standard text for
  // each licence named in their SPDX expression.
  return pkg.license
    .split(/\s+(?:AND|OR)\s+/)
    .map(id => notices.standardTexts[id.replace(/[()]/g, '')])
    .filter(Boolean);
}

export default function LicensesScreen() {
  const { settings } = useSettings();
  const palette = getPalette(settings.theme);
  const [open, setOpen] = useState(null);
  const data = useMemo(() => notices.packages, []);

  const header = (
    <View>
      {CREDITS.map(c => (
        <View key={c.id} style={[styles.card, { backgroundColor: palette.cardBg, borderColor: palette.border }]}>
          <Text style={[styles.cardTitle, { color: palette.text }]} accessibilityRole="header">{c.title}</Text>
          <Text style={[styles.body, { color: palette.text }]}>{c.body}</Text>
          {c.link && (
            <TouchableOpacity
              onPress={() => Linking.openURL(c.link.url)}
              style={styles.linkRow}
              accessibilityRole="link"
              accessibilityLabel={c.link.label}
            >
              <Text style={[styles.link, { color: palette.primary }]}>{c.link.label}</Text>
            </TouchableOpacity>
          )}
        </View>
      ))}
      <Text style={[styles.section, { color: palette.text }]} accessibilityRole="header">
        Open-source software ({data.length} packages)
      </Text>
      <Text style={[styles.body, { color: palette.textSecondary, marginBottom: spacing.sm }]}>
        Tap a package to read its licence.
      </Text>
    </View>
  );

  return (
    <FlatList
      style={{ backgroundColor: palette.background }}
      contentContainerStyle={styles.content}
      data={data}
      keyExtractor={p => p.name}
      ListHeaderComponent={header}
      initialNumToRender={20}
      renderItem={({ item }) => {
        const expanded = open === item.name;
        return (
          <View style={[styles.row, { borderBottomColor: palette.border }]}>
            <TouchableOpacity
              onPress={() => setOpen(expanded ? null : item.name)}
              style={styles.rowMain}
              accessibilityRole="button"
              accessibilityLabel={`${item.name} ${item.version}, ${item.license} licence`}
              accessibilityState={{ expanded }}
            >
              <Text style={[styles.pkg, { color: palette.text }]}>{item.name}</Text>
              <Text style={[styles.meta, { color: palette.textSecondary }]}>{item.version} · {item.license}</Text>
            </TouchableOpacity>
            {expanded && licenceTextsFor(item).map((text, i) => (
              <Text key={i} style={[styles.licence, { color: palette.text, backgroundColor: palette.surface }]} selectable>
                {text}
              </Text>
            ))}
          </View>
        );
      }}
    />
  );
}

const styles = StyleSheet.create({
  content: { padding: spacing.lg, paddingBottom: 48 },
  card: { borderWidth: 1, borderRadius: radii.md, padding: spacing.md, marginBottom: spacing.md },
  cardTitle: { fontSize: 17, fontWeight: '700', marginBottom: 4 },
  body: { fontSize: 14, lineHeight: 20 },
  linkRow: { minHeight: 44, justifyContent: 'center' },
  link: { fontSize: 15, textDecorationLine: 'underline' },
  section: { fontSize: 18, fontWeight: '700', marginTop: spacing.md, marginBottom: 4 },
  row: { borderBottomWidth: StyleSheet.hairlineWidth },
  rowMain: { minHeight: 52, justifyContent: 'center', paddingVertical: 6 },
  pkg: { fontSize: 15, fontWeight: '600' },
  meta: { fontSize: 13 },
  licence: { fontSize: 12, lineHeight: 17, padding: spacing.sm, borderRadius: radii.sm, marginBottom: spacing.sm, fontFamily: 'monospace' },
});
